# Tensorflow2.0 小练习

In [3]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [4]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    ##########
    # 将输入转换为 Tensor 类型，方便后续 TensorFlow 运算
    x = tf.convert_to_tensor(x, dtype=tf.float32)

    # 找到每一行的最大值（沿最后一维）
    # keepdims=True 可以保持维度一致，方便后续广播计算
    x_max = tf.reduce_max(x, axis=-1, keepdims=True)

    # 进行数值稳定处理：x - max(x)
    # 防止 exp(x) 过大导致溢出
    exp_x = tf.exp(x - x_max)

    # 计算每一行指数值的和
    sum_exp = tf.reduce_sum(exp_x, axis=-1, keepdims=True)

    # 按公式计算 softmax 概率
    prob_x = exp_x / sum_exp

    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [5]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    # 转换为 Tensor 类型
    x = tf.convert_to_tensor(x, dtype=tf.float32)

    # 按公式计算 sigmoid
    prob_x = 1.0 / (1.0 + tf.exp(-x))

    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [18]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    # 转换为 Tensor 类型
    x = tf.convert_to_tensor(x, dtype=tf.float64)
    label = tf.convert_to_tensor(label, dtype=tf.float64)

    # 防止 log(0)，加入一个极小值
    eps = 1e-9

    # 计算每个样本的交叉熵
    # axis=-1 表示对类别维度求和
    loss = -tf.reduce_sum(label * tf.math.log(x + eps), axis=-1)

    # 对 batch 中所有样本求平均
    loss = tf.reduce_mean(loss)

    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))- softmax_ce(prob, label))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵loss函数

In [ ]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    # 转换为 Tensor
    x = tf.convert_to_tensor(x, dtype=tf.float64)
    label = tf.convert_to_tensor(label, dtype=tf.float64)

    # 防止 log(0)
    eps = 1e-9

    # 按公式计算交叉熵
    loss = -(label * tf.math.log(x + eps) +
             (1 - label) * tf.math.log(1 - x + eps))

    # 计算 batch 平均 loss
    loss = tf.reduce_mean(loss)

    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[1. 0. 0. 1. 1. 0. 0. 0. 1. 1.]


True